# Generated by Django 3.1.6 on 2021-02-21 00:01

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warsztaty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warsztatypage',
            name='beret',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='warsztatypage',
            name='comment',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='warsztatypage',
            name='milicki',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='warsztatypage',
            name='monika',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
