# Generated by Django 3.1.6 on 2021-02-21 00:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warsztaty', '0002_auto_20210221_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='warsztatypage',
            name='opis',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='warsztatypage',
            name='zaproszenie',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
