# Generated by Django 3.1.6 on 2021-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statut', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statutpage',
            name='tytul',
        ),
        migrations.AddField(
            model_name='statutpage',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='link_text',
            field=models.TextField(blank=True),
        ),
    ]
