# Generated by Django 3.1.6 on 2021-02-19 09:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArteuniteMock',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('long_name', wagtail.fields.RichTextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('quote_author', models.TextField(blank=True)),
                ('earth_head', models.TextField(blank=True)),
                ('earth', wagtail.fields.RichTextField(blank=True)),
                ('star_head', models.TextField(blank=True)),
                ('star', wagtail.fields.RichTextField(blank=True)),
                ('flame_head', models.TextField(blank=True)),
                ('flame', wagtail.fields.RichTextField(blank=True)),
                ('wolna_ziemia', wagtail.fields.RichTextField(blank=True)),
                ('stodola', wagtail.fields.RichTextField(blank=True)),
                ('workshop', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
