# Generated by Django 3.1.6 on 2021-03-03 05:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_arteunitemock'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='filozofia',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
