# Generated by Django 3.1.6 on 2021-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolacz', '0002_auto_20210306_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=1024, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('find_us', models.CharField(max_length=1024, null=True)),
                ('newsletter', models.BooleanField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
